ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "chaski"
  site-url: "https://enzokro.github.io/chaski"
  description: "blog"
  twitter-card: true
  open-graph: true
  reader-mode: true
  repo-branch: master
  repo-url: "https://github.com/enzokro/chaski"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/enzokro/chaski"

metadata-files: 
  - sidebar.yml
  - custom.yml
