project:
  type: website

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-depth: 4

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  favicon: favicon.png
  navbar:
    left:
      - text: "Blog"
        href: blog/index.qmd
      - text: "About"
        href: repo_index.ipynb
    background: primary
    search: true
  sidebar:
    style: floating

metadata-files: [nbdev.yml]