project:
  type: website

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-depth: 4

website:
  site-url: https://enzokro.dev
  description: "Enzo's personal Blog."
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  favicon: favicon.png
  navbar:
    left:
      - text: "Blog"
        href: blog/index.qmd
    right:
      - icon: github
        href: "https://github.com/enzokro/chaski"
    background: primary
    search: true
  sidebar:
    style: floating

metadata-files: [nbdev.yml]