project:
  type: website
  output-dir: _docs
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!api/"
    - "!drafts/"

format:
  html:
    theme: litera
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "chaski"
  description: "Enzo's site."
  site-url: "https://enzokro.dev"
  repo-branch: master
  repo-url: "https://github.com/enzokro/chaski"
  repo-actions: [issue]
  twitter-card: true
  open-graph: true
  favicon: favicon.png
  navbar:
    pinned: true
    left:
      - text: "About"
        href: about.ipynb
        icon: person-circle
    right:
      - icon: twitter
        href: "https://twitter.com/enzokro_"
      - icon: github
        href: "https://github.com/enzokro"
    background: primary
    search: true