project:
  type: website
  output-dir: _docs
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!blog/api/"
    - "!drafts/"

format:
  html:
    theme: litera
    css: styles.css
    toc: true
    toc-depth: 4
    include-in-header: 
      - ./custom-header.ejs
    # code-overflow: wrap
    highlight-style: 
      light: assets/pygments.theme
      dark: assets/pygments.theme


website:
  title: "chaski"
  description: "Enzo's site."
  site-url: "https://enzokro.dev"
  repo-branch: master
  repo-url: "https://github.com/enzokro/chaski"
  repo-actions: [issue]
  twitter-card: true
  open-graph: true
  favicon: favicon.png
  navbar:
    pinned: true
    right:
      - icon: twitter
        href: "https://twitter.com/enzokro_"
      - icon: github
        href: "https://github.com/enzokro"
    background: "transparent"
    search: true