project:
  type: website

format:
  html:
    theme: cosmo
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    left:
      - text: "Blog"
        href: blog/index.qmd
    background: primary
    search: true
  sidebar:
    style: floating

metadata-files: [nbdev.yml]