# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/chaski',
                'doc_host': 'https://enzokro.github.io',
                'git_url': 'https://github.com/enzokro/chaski',
                'lib_path': 'chaski'},
  'syms': {'chaski.complexRayleighInit': {}, 'chaski.diffusionIntroPost': {}, 'chaski.normalizingSpectrogramsPost': {}}}