# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/chaski',
                'doc_host': 'https://enzokro.github.io',
                'git_url': 'https://github.com/enzokro/chaski',
                'lib_path': 'chaski'},
  'syms': { 'chaski.complex_init': { 'chaski.complex_init._calculate_fan_in_and_fan_out_from_shape': ( 'api/complex_inits.html#_calculate_fan_in_and_fan_out_from_shape',
                                                                                                       'chaski/complex_init.py'),
                                     'chaski.complex_init.get_complex_inits': ( 'api/complex_inits.html#get_complex_inits',
                                                                                'chaski/complex_init.py')}}}