# AUTOGENERATED! DO NOT EDIT! File to edit: ../content/03_normalizingSpectrogramsPost.ipynb.

# %% auto 0
__all__ = []

# %% ../content/03_normalizingSpectrogramsPost.ipynb 3
import matplotlib.pyplot as plt
import numpy as np
