# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/blog/posts/03_normalizingSpectrogramsPost.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/blog/posts/03_normalizingSpectrogramsPost.ipynb 3
import matplotlib.pyplot as plt
import numpy as np
